---

- hosts: "{{ DTMS_INSTALLATION_NAME }}"
  tasks:
    - name: Init
      vars:
        title: "Инициализация"
        description: "Инициализация"
      include_role: 
        name: "{{ DTMS_INSTALLATION_NAME }}"
        tasks_from: init.yaml
    - name: Restart "{{ DTMS_INSTALLATION_NAME }}"
      vars:
        title: "Перезапуск приложения"
        description: "Перезапуск приложения"
      include_role:
        name: "{{ DTMS_INSTALLATION_NAME }}"
        tasks_from: restart.yaml
